version: "3.9"

services:
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_ADMIN_ENABLED=true

  grafana:
    image: grafana/grafana:11.1.0
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning

  load-api:
    build: ./load-api
    ports:
      - "3000:3000"
    volumes:
      - ./scenarios:/scripts
    depends_on:
      - influxdb

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  target-server:
    build: ./target-server
    ports:
      - "4000:4000"

  k6:
    image: grafana/k6
    volumes:
      - ./scenarios:/scripts
    networks:
      - default
