global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # 필요 시, 여러분의 앱 /actuator/prometheus 등 추가
  # - job_name: 'spring-app'
  #   metrics_path: /actuator/prometheus
  #   static_configs:
  #     - targets: ['dev-worker:8080']
